name 'puppet-stringed'
version '0.0.1'
source 'git://github.com/Bitlancer/puppet-stringed.git'
author 'bitlancer'
summary 'Bitlancer Strings Puppet profiles'
project_page 'https://github.com/Bitlancer/puppet-stringed'
dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/firewall'
dependency 'bitlancer/sssd'
